

ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_avalon_st_adapter_001_error_adapter_0.sv" -work error_adapter_0                                     -cdslib <<error_adapter_0>>                                    
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv"     -work error_adapter_0                                     -cdslib <<error_adapter_0>>                                    
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_avalon_st_adapter_001.vhd"                -work avalon_st_adapter_001                               -cdslib <<avalon_st_adapter_001>>                              
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_avalon_st_adapter.vhd"                    -work avalon_st_adapter                                   -cdslib <<avalon_st_adapter>>                                  
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_handshake_clock_crosser.v"                              -work crosser                                             -cdslib <<crosser>>                                            
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_clock_crosser.v"                                        -work crosser                                             -cdslib <<crosser>>                                            
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_pipeline_base.v"                                        -work crosser                                             -cdslib <<crosser>>                                            
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_std_synchronizer_nocut.v"                                         -work crosser                                             -cdslib <<crosser>>                                            
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_width_adapter.sv"                                          -work sram_0_avalon_sram_slave_rsp_width_adapter          -cdslib <<sram_0_avalon_sram_slave_rsp_width_adapter>>         
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_address_alignment.sv"                                      -work sram_0_avalon_sram_slave_rsp_width_adapter          -cdslib <<sram_0_avalon_sram_slave_rsp_width_adapter>>         
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_burst_uncompressor.sv"                                     -work sram_0_avalon_sram_slave_rsp_width_adapter          -cdslib <<sram_0_avalon_sram_slave_rsp_width_adapter>>         
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_rsp_mux_001.sv"                           -work rsp_mux_001                                         -cdslib <<rsp_mux_001>>                                        
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_arbitrator.sv"                                             -work rsp_mux_001                                         -cdslib <<rsp_mux_001>>                                        
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_rsp_mux.sv"                               -work rsp_mux                                             -cdslib <<rsp_mux>>                                            
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_arbitrator.sv"                                             -work rsp_mux                                             -cdslib <<rsp_mux>>                                            
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_rsp_demux_001.sv"                         -work rsp_demux_001                                       -cdslib <<rsp_demux_001>>                                      
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_rsp_demux.sv"                             -work rsp_demux                                           -cdslib <<rsp_demux>>                                          
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_cmd_mux_001.sv"                           -work cmd_mux_001                                         -cdslib <<cmd_mux_001>>                                        
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_arbitrator.sv"                                             -work cmd_mux_001                                         -cdslib <<cmd_mux_001>>                                        
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_cmd_mux.sv"                               -work cmd_mux                                             -cdslib <<cmd_mux>>                                            
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_arbitrator.sv"                                             -work cmd_mux                                             -cdslib <<cmd_mux>>                                            
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_cmd_demux_001.sv"                         -work cmd_demux_001                                       -cdslib <<cmd_demux_001>>                                      
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_cmd_demux.sv"                             -work cmd_demux                                           -cdslib <<cmd_demux>>                                          
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_burst_adapter.sv"                                          -work sram_0_avalon_sram_slave_burst_adapter              -cdslib <<sram_0_avalon_sram_slave_burst_adapter>>             
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_burst_adapter_uncmpr.sv"                                   -work sram_0_avalon_sram_slave_burst_adapter              -cdslib <<sram_0_avalon_sram_slave_burst_adapter>>             
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_burst_adapter_13_1.sv"                                     -work sram_0_avalon_sram_slave_burst_adapter              -cdslib <<sram_0_avalon_sram_slave_burst_adapter>>             
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_burst_adapter_new.sv"                                      -work sram_0_avalon_sram_slave_burst_adapter              -cdslib <<sram_0_avalon_sram_slave_burst_adapter>>             
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_incr_burst_converter.sv"                                          -work sram_0_avalon_sram_slave_burst_adapter              -cdslib <<sram_0_avalon_sram_slave_burst_adapter>>             
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_wrap_burst_converter.sv"                                          -work sram_0_avalon_sram_slave_burst_adapter              -cdslib <<sram_0_avalon_sram_slave_burst_adapter>>             
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_default_burst_converter.sv"                                       -work sram_0_avalon_sram_slave_burst_adapter              -cdslib <<sram_0_avalon_sram_slave_burst_adapter>>             
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_address_alignment.sv"                                      -work sram_0_avalon_sram_slave_burst_adapter              -cdslib <<sram_0_avalon_sram_slave_burst_adapter>>             
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_pipeline_stage.sv"                                      -work sram_0_avalon_sram_slave_burst_adapter              -cdslib <<sram_0_avalon_sram_slave_burst_adapter>>             
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_pipeline_base.v"                                        -work sram_0_avalon_sram_slave_burst_adapter              -cdslib <<sram_0_avalon_sram_slave_burst_adapter>>             
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_traffic_limiter.sv"                                        -work ensamblado_procesador_0_avalon_master_limiter       -cdslib <<ensamblado_procesador_0_avalon_master_limiter>>      
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_reorder_memory.sv"                                         -work ensamblado_procesador_0_avalon_master_limiter       -cdslib <<ensamblado_procesador_0_avalon_master_limiter>>      
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_sc_fifo.v"                                                 -work ensamblado_procesador_0_avalon_master_limiter       -cdslib <<ensamblado_procesador_0_avalon_master_limiter>>      
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_pipeline_base.v"                                        -work ensamblado_procesador_0_avalon_master_limiter       -cdslib <<ensamblado_procesador_0_avalon_master_limiter>>      
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_router_004.sv"                            -work router_004                                          -cdslib <<router_004>>                                         
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_router_003.sv"                            -work router_003                                          -cdslib <<router_003>>                                         
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_router_001.sv"                            -work router_001                                          -cdslib <<router_001>>                                         
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0_router.sv"                                -work router                                              -cdslib <<router>>                                             
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_slave_agent.sv"                                            -work sram_0_avalon_sram_slave_agent                      -cdslib <<sram_0_avalon_sram_slave_agent>>                     
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_burst_uncompressor.sv"                                     -work sram_0_avalon_sram_slave_agent                      -cdslib <<sram_0_avalon_sram_slave_agent>>                     
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_master_agent.sv"                                           -work video_dma_controller_0_avalon_dma_master_agent      -cdslib <<video_dma_controller_0_avalon_dma_master_agent>>     
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_slave_translator.sv"                                       -work sram_0_avalon_sram_slave_translator                 -cdslib <<sram_0_avalon_sram_slave_translator>>                
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_merlin_master_translator.sv"                                      -work video_dma_controller_0_avalon_dma_master_translator -cdslib <<video_dma_controller_0_avalon_dma_master_translator>>
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_up_avalon_reset_from_locked_signal.v"                             -work reset_from_locked                                   -cdslib <<reset_from_locked>>                                  
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_up_altpll.v"                                                      -work sys_pll                                             -cdslib <<sys_pll>>                                            
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_master_0_p2b_adapter.sv"                                    -work p2b_adapter                                         -cdslib <<p2b_adapter>>                                        
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_master_0_b2p_adapter.sv"                                    -work b2p_adapter                                         -cdslib <<b2p_adapter>>                                        
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_packets_to_master.v"                                       -work transacto                                           -cdslib <<transacto>>                                          
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_packets_to_bytes.v"                                     -work p2b                                                 -cdslib <<p2b>>                                                
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_bytes_to_packets.v"                                     -work b2p                                                 -cdslib <<b2p>>                                                
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_sc_fifo.v"                                                 -work fifo                                                -cdslib <<fifo>>                                               
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_master_0_timing_adt.sv"                                     -work timing_adt                                          -cdslib <<timing_adt>>                                         
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_jtag_interface.v"                                       -work jtag_phy_embedded_in_jtag_master                    -cdslib <<jtag_phy_embedded_in_jtag_master>>                   
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_jtag_dc_streaming.v"                                              -work jtag_phy_embedded_in_jtag_master                    -cdslib <<jtag_phy_embedded_in_jtag_master>>                   
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_jtag_sld_node.v"                                                  -work jtag_phy_embedded_in_jtag_master                    -cdslib <<jtag_phy_embedded_in_jtag_master>>                   
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_jtag_streaming.v"                                                 -work jtag_phy_embedded_in_jtag_master                    -cdslib <<jtag_phy_embedded_in_jtag_master>>                   
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_clock_crosser.v"                                        -work jtag_phy_embedded_in_jtag_master                    -cdslib <<jtag_phy_embedded_in_jtag_master>>                   
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_std_synchronizer_nocut.v"                                         -work jtag_phy_embedded_in_jtag_master                    -cdslib <<jtag_phy_embedded_in_jtag_master>>                   
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_pipeline_base.v"                                        -work jtag_phy_embedded_in_jtag_master                    -cdslib <<jtag_phy_embedded_in_jtag_master>>                   
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_idle_remover.v"                                         -work jtag_phy_embedded_in_jtag_master                    -cdslib <<jtag_phy_embedded_in_jtag_master>>                   
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_idle_inserter.v"                                        -work jtag_phy_embedded_in_jtag_master                    -cdslib <<jtag_phy_embedded_in_jtag_master>>                   
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_avalon_st_pipeline_stage.sv"                                      -work jtag_phy_embedded_in_jtag_master                    -cdslib <<jtag_phy_embedded_in_jtag_master>>                   
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_reset_controller.v"                                               -work rst_controller                                      -cdslib <<rst_controller>>                                     
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/altera_reset_synchronizer.v"                                             -work rst_controller                                      -cdslib <<rst_controller>>                                     
ncvlog -sv  "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_irq_mapper.sv"                                              -work irq_mapper                                          -cdslib <<irq_mapper>>                                         
ncvlog      "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_mm_interconnect_0.v"                                        -work mm_interconnect_0                                   -cdslib <<mm_interconnect_0>>                                  
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_video_pll_0.vhd"                                            -work video_pll_0                                         -cdslib <<video_pll_0>>                                        
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_sys_sdram_pll_0.vhd"                                        -work sys_sdram_pll_0                                     -cdslib <<sys_sdram_pll_0>>                                    
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_new_sdram_controller_0_test_component.vhd"                  -work new_sdram_controller_0                              -cdslib <<new_sdram_controller_0>>                             
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_new_sdram_controller_0.vhd"                                 -work new_sdram_controller_0                              -cdslib <<new_sdram_controller_0>>                             
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_master_0.vhd"                                               -work master_0                                            -cdslib <<master_0>>                                           
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/constantes.vhd"                                                          -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/retardos.vhd"                                                            -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/tipos.vhd"                                                               -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/mux2_32.vhd"                                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/mux3_32.vhd"                                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/reg32.vhd"                                                               -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/reg32pe.vhd"                                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/mux4_32.vhd"                                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/componentes_procesador.vhd"                                              -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/ensamblado_procesador.vhd"                                               -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/componentesUC.vhd"                                                       -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/ensambladoUC.vhd"                                                        -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/automata_estado.vhd"                                                     -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/componentes_decoder.vhd"                                                 -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/decoder.vhd"                                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/decoExcep.vhd"                                                           -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/decoFMT.vhd"                                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/decoMem.vhd"                                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/decoSec.vhd"                                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/decocamino.vhd"                                                          -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/decoopALU.vhd"                                                           -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/componentesUP.vhd"                                                       -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/ensambladoUP.vhd"                                                        -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/ALU.vhd"                                                                 -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/BR.vhd"                                                                  -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/FMTE.vhd"                                                                -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/FMTI.vhd"                                                                -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/FMTL.vhd"                                                                -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/fuerza_bit_0.vhd"                                                        -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/componentesSYS.vhd"                                                      -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/ensambladoSYS.vhd"                                                       -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/BR_CSR.vhd"                                                              -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/ALU_CSR.vhd"                                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/camino_SYS.vhd"                                                          -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/componentes_camino_SYS.vhd"                                              -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/componentes_control_SYS.vhd"                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/control_SYS.vhd"                                                         -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/automata_estado_SYS.vhd"                                                 -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/componentes_decoSYS.vhd"                                                 -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/decoSYS.vhd"                                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/decoCamino_SYS.vhd"                                                      -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/decoExcep_SYS.vhd"                                                       -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/gestorEventos.vhd"                                                       -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/PLIC.vhd"                                                                -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/PLIC_core.vhd"                                                           -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/gateway.vhd"                                                             -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/PLIC_gateway.vhd"                                                        -work ensamblado_procesador_0                             -cdslib <<ensamblado_procesador_0>>                            
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/submodules/disenyo_qsys_altpll_0.vho"                                               -work altpll_0                                            -cdslib <<altpll_0>>                                           
ncvhdl -v93 "/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/simulation/disenyo_qsys.vhd"                                                                                                                                                                                            
