transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib disenyo_qsys
vmap disenyo_qsys disenyo_qsys
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/disenyo_qsys.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_avalon_packets_to_master.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_avalon_st_bytes_to_packets.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_avalon_st_idle_inserter.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_avalon_st_idle_remover.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_avalon_st_jtag_interface.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_avalon_st_packets_to_bytes.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_jtag_dc_streaming.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_jtag_sld_node.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_jtag_streaming.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_reset_controller.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_up_altpll.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_up_avalon_reset_from_locked_signal.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_up_avalon_video_vga_timing.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_up_ps2.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_up_ps2_command_out.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_up_ps2_data_in.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_up_video_dma_control_slave.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_up_video_dma_to_stream.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_altpll_0.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_master_0.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_avalon_st_adapter_001.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_new_sdram_controller_0.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_ps2_0.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_sram_0.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_sys_sdram_pll_0.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_video_dma_controller_0.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_video_dual_clock_buffer_0.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_video_pll_0.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_video_vga_controller_0.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_avalon_st_handshake_clock_crosser.v}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_avalon_st_pipeline_base.v}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_merlin_burst_adapter_uncmpr.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_merlin_master_agent.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_merlin_master_translator.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_merlin_traffic_limiter.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_merlin_width_adapter.sv}
vlog -vlog01compat -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/altera_std_synchronizer_nocut.v}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_irq_mapper.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_master_0_b2p_adapter.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_master_0_p2b_adapter.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_master_0_timing_adt.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_avalon_st_adapter_001_error_adapter_0.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_cmd_mux_001.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_router.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_router_001.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_router_003.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_router_004.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_rsp_demux_001.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work disenyo_qsys +incdir+/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/disenyo_qsys_mm_interconnect_0_rsp_mux_001.sv}
vcom -93 -work work {/home/gerard/Desktop/clase/TFG/proyecto/CODIGO/ensamblado_placa/ensamblado_placa.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/constantes.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/retardos.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/tipos.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/ALU.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/ALU_CSR.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/BR.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/BR_CSR_procedimientos.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/CLINT.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/FMTE.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/FMTI.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/FMTL.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/automata_estado_SYS.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/automata_estado_procedimientos_pkg.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/componentesSYS.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/componentesUC.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/componentesUP.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/componentes_camino_SYS.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/componentes_control_SYS.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/componentes_decoSYS.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/componentes_decoder.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/componentes_procesador.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/decoCamino_SYS.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/decoExcep.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/decoExcep_SYS.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/decoder_procedimientos_pkg.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/decoopALU.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/fuerza_bit_0.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/gestorEventos.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/mux2_32.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/mux3_32.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/reg32.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/reg32pe.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/BR_CSR.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/automata_estado.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/camino_SYS.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/control_SYS.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/decoFMT.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/decoMem.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/decoSYS.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/decoSec.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/decocamino.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/decoder.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/ensambladoSYS.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/ensambladoUC.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/ensambladoUP.vhd}
vcom -93 -work disenyo_qsys {/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/db/ip/disenyo_qsys/submodules/ensamblado_procesador.vhd}

do "/home/gerard/Desktop/clase/TFG/proyecto/pruebas_y_quartus/ensamblado_placa/QUARTUS/../../../CODIGO/ensamblado_placa/COMPONENTES/disenyo_qsys/disenyo_qsys/testbench/mentor/msim_setup.tcl"
