# TCL File Generated by Component Editor 19.1
# Fri Jun 05 17:07:05 CEST 2020
# DO NOT MODIFY


# 
# ensamblado_procesador "ensamblado_procesador" v1.0
#  2020.06.05.17:07:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ensamblado_procesador
# 
set_module_property DESCRIPTION ""
set_module_property NAME ensamblado_procesador
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ensamblado_procesador
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ensamblado_procesador
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file constantes.vhd VHDL PATH ../../../../ip/procesador/parametros/constantes.vhd
add_fileset_file retardos.vhd VHDL PATH ../../../../ip/procesador/parametros/retardos.vhd
add_fileset_file tipos.vhd VHDL PATH ../../../../ip/procesador/parametros/tipos.vhd
add_fileset_file componentes_procesador.vhd VHDL PATH ../../../../ip/procesador/componentes_procesador.vhd
add_fileset_file ensamblado_procesador.vhd VHDL PATH ../../../../ip/procesador/ensamblado_procesador.vhd TOP_LEVEL_FILE
add_fileset_file mux2_32.vhd VHDL PATH ../../../../ip/procesador/componentes_elementales/mux2_32.vhd
add_fileset_file mux3_32.vhd VHDL PATH ../../../../ip/procesador/componentes_elementales/mux3_32.vhd
add_fileset_file mux4_32.vhd VHDL PATH ../../../../ip/procesador/componentes_elementales/mux4_32.vhd
add_fileset_file reg32.vhd VHDL PATH ../../../../ip/procesador/componentes_elementales/reg32.vhd
add_fileset_file reg32pe.vhd VHDL PATH ../../../../ip/procesador/componentes_elementales/reg32pe.vhd
add_fileset_file componentesUP.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/componentesUP.vhd
add_fileset_file ensambladoUP.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/ensambladoUP.vhd
add_fileset_file ALU.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/ALU.vhd
add_fileset_file BR.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/BR.vhd
add_fileset_file FMTE.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/FMTE.vhd
add_fileset_file FMTI.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/FMTI.vhd
add_fileset_file FMTL.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/FMTL.vhd
add_fileset_file fuerza_bit_0.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/fuerza_bit_0.vhd
add_fileset_file componentesUC.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/componentesUC.vhd
add_fileset_file ensambladoUC.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/ensambladoUC.vhd
add_fileset_file automata_estado_procedimientos_pkg.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/automata_estado/automata_estado_procedimientos_pkg.vhd
add_fileset_file automata_estado.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/automata_estado/automata_estado.vhd
add_fileset_file decoder_procedimientos_pkg.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/decoder_procedimientos_pkg.vhd
add_fileset_file componentes_decoder.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/componentes_decoder.vhd
add_fileset_file decoder.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/decoder.vhd
add_fileset_file decoExcep.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decoExcep.vhd
add_fileset_file decoFMT.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decoFMT.vhd
add_fileset_file decoMem.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decoMem.vhd
add_fileset_file decoSec.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decoSec.vhd
add_fileset_file decocamino.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decocamino.vhd
add_fileset_file decoopALU.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decoopALU.vhd
add_fileset_file componentesSYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/componentesSYS.vhd
add_fileset_file ensambladoSYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/ensambladoSYS.vhd
add_fileset_file BR_CSR_procedimientos.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/BR_CSR/BR_CSR_procedimientos.vhd
add_fileset_file BR_CSR.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/BR_CSR/BR_CSR.vhd
add_fileset_file componentes_camino_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/camino_SYS/componentes_camino_SYS.vhd
add_fileset_file camino_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/camino_SYS/camino_SYS.vhd
add_fileset_file ALU_CSR.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/camino_SYS/COMPONENTES/ALU_CSR.vhd
add_fileset_file componentes_control_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/componentes_control_SYS.vhd
add_fileset_file control_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/control_SYS.vhd
add_fileset_file componentes_decoSYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/COMPONENTES/decoSYS/componentes_decoSYS.vhd
add_fileset_file decoSYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/COMPONENTES/decoSYS/decoSYS.vhd
add_fileset_file decoCamino_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/COMPONENTES/decoSYS/COMPONENTES/decoCamino_SYS.vhd
add_fileset_file decoExcep_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/COMPONENTES/decoSYS/COMPONENTES/decoExcep_SYS.vhd
add_fileset_file automata_estado_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/COMPONENTES/automata_estado_SYS/automata_estado_SYS.vhd
add_fileset_file recolectorEventos.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/recolectorEventos/recolectorEventos.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL ensamblado_procesador
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file constantes.vhd VHDL PATH ../../../../ip/procesador/parametros/constantes.vhd
add_fileset_file retardos.vhd VHDL PATH ../../../../ip/procesador/parametros/retardos.vhd
add_fileset_file tipos.vhd VHDL PATH ../../../../ip/procesador/parametros/tipos.vhd
add_fileset_file componentes_procesador.vhd VHDL PATH ../../../../ip/procesador/componentes_procesador.vhd
add_fileset_file ensamblado_procesador.vhd VHDL PATH ../../../../ip/procesador/ensamblado_procesador.vhd
add_fileset_file mux2_32.vhd VHDL PATH ../../../../ip/procesador/componentes_elementales/mux2_32.vhd
add_fileset_file mux3_32.vhd VHDL PATH ../../../../ip/procesador/componentes_elementales/mux3_32.vhd
add_fileset_file mux4_32.vhd VHDL PATH ../../../../ip/procesador/componentes_elementales/mux4_32.vhd
add_fileset_file reg32.vhd VHDL PATH ../../../../ip/procesador/componentes_elementales/reg32.vhd
add_fileset_file reg32pe.vhd VHDL PATH ../../../../ip/procesador/componentes_elementales/reg32pe.vhd
add_fileset_file componentesUP.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/componentesUP.vhd
add_fileset_file ensambladoUP.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/ensambladoUP.vhd
add_fileset_file ALU.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/ALU.vhd
add_fileset_file BR.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/BR.vhd
add_fileset_file FMTE.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/FMTE.vhd
add_fileset_file FMTI.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/FMTI.vhd
add_fileset_file FMTL.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/FMTL.vhd
add_fileset_file fuerza_bit_0.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UP/COMPONENTES/fuerza_bit_0.vhd
add_fileset_file componentesUC.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/componentesUC.vhd
add_fileset_file ensambladoUC.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/ensambladoUC.vhd
add_fileset_file automata_estado_procedimientos_pkg.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/automata_estado/automata_estado_procedimientos_pkg.vhd
add_fileset_file automata_estado.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/automata_estado/automata_estado.vhd
add_fileset_file decoder_procedimientos_pkg.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/decoder_procedimientos_pkg.vhd
add_fileset_file componentes_decoder.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/componentes_decoder.vhd
add_fileset_file decoder.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/decoder.vhd
add_fileset_file decoExcep.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decoExcep.vhd
add_fileset_file decoFMT.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decoFMT.vhd
add_fileset_file decoMem.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decoMem.vhd
add_fileset_file decoSec.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decoSec.vhd
add_fileset_file decocamino.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decocamino.vhd
add_fileset_file decoopALU.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/UC/COMPONENTES/DECODER/COMPONENTES/decoopALU.vhd
add_fileset_file componentesSYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/componentesSYS.vhd
add_fileset_file ensambladoSYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/ensambladoSYS.vhd
add_fileset_file BR_CSR_procedimientos.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/BR_CSR/BR_CSR_procedimientos.vhd
add_fileset_file BR_CSR.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/BR_CSR/BR_CSR.vhd
add_fileset_file componentes_camino_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/camino_SYS/componentes_camino_SYS.vhd
add_fileset_file camino_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/camino_SYS/camino_SYS.vhd
add_fileset_file ALU_CSR.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/camino_SYS/COMPONENTES/ALU_CSR.vhd
add_fileset_file componentes_control_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/componentes_control_SYS.vhd
add_fileset_file control_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/control_SYS.vhd
add_fileset_file componentes_decoSYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/COMPONENTES/decoSYS/componentes_decoSYS.vhd
add_fileset_file decoSYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/COMPONENTES/decoSYS/decoSYS.vhd
add_fileset_file decoCamino_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/COMPONENTES/decoSYS/COMPONENTES/decoCamino_SYS.vhd
add_fileset_file decoExcep_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/COMPONENTES/decoSYS/COMPONENTES/decoExcep_SYS.vhd
add_fileset_file automata_estado_SYS.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/control_SYS/COMPONENTES/automata_estado_SYS/automata_estado_SYS.vhd
add_fileset_file recolectorEventos.vhd VHDL PATH ../../../../ip/procesador/COMPONENTES/USYS/COMPONENTES/recolectorEventos/recolectorEventos.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master address address Output 32
add_interface_port avalon_master writedata writedata Output 32
add_interface_port avalon_master readdata readdata Input 32
add_interface_port avalon_master read read Output 1
add_interface_port avalon_master write write Output 1
add_interface_port avalon_master byteenable byteenable Output 4
add_interface_port avalon_master waitrequest waitrequest Input 1
add_interface_port avalon_master readdatavalid readdatavalid Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink reloj clk Input 1


# 
# connection point interrupt_receiver
# 
add_interface interrupt_receiver interrupt start
set_interface_property interrupt_receiver associatedAddressablePoint ""
set_interface_property interrupt_receiver associatedClock clock_sink
set_interface_property interrupt_receiver associatedReset reset
set_interface_property interrupt_receiver irqScheme INDIVIDUAL_REQUESTS
set_interface_property interrupt_receiver ENABLED true
set_interface_property interrupt_receiver EXPORT_OF ""
set_interface_property interrupt_receiver PORT_NAME_MAP ""
set_interface_property interrupt_receiver CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_receiver SVD_ADDRESS_GROUP ""

add_interface_port interrupt_receiver irq irq Input 2


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end start bit Input 1

