// disenyo_qsys_tb.v

// Generated using ACDS version 19.1 670

`timescale 1 ps / 1 ps
module disenyo_qsys_tb (
	);

	wire         disenyo_qsys_inst_clk_bfm_clk_clk;                 // disenyo_qsys_inst_clk_bfm:clk -> [disenyo_qsys_inst:clk_clk, disenyo_qsys_inst_reset_bfm:clk]
	wire         new_sdram_controller_0_my_partner_clk_bfm_clk_clk; // new_sdram_controller_0_my_partner_clk_bfm:clk -> new_sdram_controller_0_my_partner:clk
	wire         disenyo_qsys_inst_sdram_wire_cs_n;                 // disenyo_qsys_inst:sdram_wire_cs_n -> new_sdram_controller_0_my_partner:zs_cs_n
	wire   [3:0] disenyo_qsys_inst_sdram_wire_dqm;                  // disenyo_qsys_inst:sdram_wire_dqm -> new_sdram_controller_0_my_partner:zs_dqm
	wire         disenyo_qsys_inst_sdram_wire_cas_n;                // disenyo_qsys_inst:sdram_wire_cas_n -> new_sdram_controller_0_my_partner:zs_cas_n
	wire         disenyo_qsys_inst_sdram_wire_ras_n;                // disenyo_qsys_inst:sdram_wire_ras_n -> new_sdram_controller_0_my_partner:zs_ras_n
	wire         disenyo_qsys_inst_sdram_wire_we_n;                 // disenyo_qsys_inst:sdram_wire_we_n -> new_sdram_controller_0_my_partner:zs_we_n
	wire  [12:0] disenyo_qsys_inst_sdram_wire_addr;                 // disenyo_qsys_inst:sdram_wire_addr -> new_sdram_controller_0_my_partner:zs_addr
	wire         disenyo_qsys_inst_sdram_wire_cke;                  // disenyo_qsys_inst:sdram_wire_cke -> new_sdram_controller_0_my_partner:zs_cke
	wire  [31:0] disenyo_qsys_inst_sdram_wire_dq;                   // [] -> [disenyo_qsys_inst:sdram_wire_dq, new_sdram_controller_0_my_partner:zs_dq]
	wire   [1:0] disenyo_qsys_inst_sdram_wire_ba;                   // disenyo_qsys_inst:sdram_wire_ba -> new_sdram_controller_0_my_partner:zs_ba
	wire         disenyo_qsys_inst_reset_bfm_reset_reset;           // disenyo_qsys_inst_reset_bfm:reset -> disenyo_qsys_inst:reset_reset_n

	disenyo_qsys disenyo_qsys_inst (
		.clk_clk             (disenyo_qsys_inst_clk_bfm_clk_clk),       //             clk.clk
		.pll_clk_100_mhz_clk (),                                        // pll_clk_100_mhz.clk
		.pll_locked_export   (),                                        //      pll_locked.export
		.pll_reset_export    (),                                        //       pll_reset.export
		.pll_slave_read      (),                                        //       pll_slave.read
		.pll_slave_write     (),                                        //                .write
		.pll_slave_address   (),                                        //                .address
		.pll_slave_readdata  (),                                        //                .readdata
		.pll_slave_writedata (),                                        //                .writedata
		.ps2_CLK             (),                                        //             ps2.CLK
		.ps2_DAT             (),                                        //                .DAT
		.reset_reset_n       (disenyo_qsys_inst_reset_bfm_reset_reset), //           reset.reset_n
		.sdram_clk_clk       (),                                        //       sdram_clk.clk
		.sdram_wire_addr     (disenyo_qsys_inst_sdram_wire_addr),       //      sdram_wire.addr
		.sdram_wire_ba       (disenyo_qsys_inst_sdram_wire_ba),         //                .ba
		.sdram_wire_cas_n    (disenyo_qsys_inst_sdram_wire_cas_n),      //                .cas_n
		.sdram_wire_cke      (disenyo_qsys_inst_sdram_wire_cke),        //                .cke
		.sdram_wire_cs_n     (disenyo_qsys_inst_sdram_wire_cs_n),       //                .cs_n
		.sdram_wire_dq       (disenyo_qsys_inst_sdram_wire_dq),         //                .dq
		.sdram_wire_dqm      (disenyo_qsys_inst_sdram_wire_dqm),        //                .dqm
		.sdram_wire_ras_n    (disenyo_qsys_inst_sdram_wire_ras_n),      //                .ras_n
		.sdram_wire_we_n     (disenyo_qsys_inst_sdram_wire_we_n),       //                .we_n
		.sram_DQ             (),                                        //            sram.DQ
		.sram_ADDR           (),                                        //                .ADDR
		.sram_LB_N           (),                                        //                .LB_N
		.sram_UB_N           (),                                        //                .UB_N
		.sram_CE_N           (),                                        //                .CE_N
		.sram_OE_N           (),                                        //                .OE_N
		.sram_WE_N           (),                                        //                .WE_N
		.start_bit           (),                                        //           start.bit
		.vga_CLK             (),                                        //             vga.CLK
		.vga_HS              (),                                        //                .HS
		.vga_VS              (),                                        //                .VS
		.vga_BLANK           (),                                        //                .BLANK
		.vga_SYNC            (),                                        //                .SYNC
		.vga_R               (),                                        //                .R
		.vga_G               (),                                        //                .G
		.vga_B               ()                                         //                .B
	);

	altera_avalon_clock_source #(
		.CLOCK_RATE (50000000),
		.CLOCK_UNIT (1)
	) disenyo_qsys_inst_clk_bfm (
		.clk (disenyo_qsys_inst_clk_bfm_clk_clk)  // clk.clk
	);

	altera_avalon_reset_source #(
		.ASSERT_HIGH_RESET    (0),
		.INITIAL_RESET_CYCLES (50)
	) disenyo_qsys_inst_reset_bfm (
		.reset (disenyo_qsys_inst_reset_bfm_reset_reset), // reset.reset_n
		.clk   (disenyo_qsys_inst_clk_bfm_clk_clk)        //   clk.clk
	);

	altera_sdram_partner_module new_sdram_controller_0_my_partner (
		.clk      (new_sdram_controller_0_my_partner_clk_bfm_clk_clk), //     clk.clk
		.zs_dq    (disenyo_qsys_inst_sdram_wire_dq),                   // conduit.dq
		.zs_addr  (disenyo_qsys_inst_sdram_wire_addr),                 //        .addr
		.zs_ba    (disenyo_qsys_inst_sdram_wire_ba),                   //        .ba
		.zs_cas_n (disenyo_qsys_inst_sdram_wire_cas_n),                //        .cas_n
		.zs_cke   (disenyo_qsys_inst_sdram_wire_cke),                  //        .cke
		.zs_cs_n  (disenyo_qsys_inst_sdram_wire_cs_n),                 //        .cs_n
		.zs_dqm   (disenyo_qsys_inst_sdram_wire_dqm),                  //        .dqm
		.zs_ras_n (disenyo_qsys_inst_sdram_wire_ras_n),                //        .ras_n
		.zs_we_n  (disenyo_qsys_inst_sdram_wire_we_n)                  //        .we_n
	);

	altera_avalon_clock_source #(
		.CLOCK_RATE (50000000),
		.CLOCK_UNIT (1)
	) new_sdram_controller_0_my_partner_clk_bfm (
		.clk (new_sdram_controller_0_my_partner_clk_bfm_clk_clk)  // clk.clk
	);

endmodule
